" VIMRC

set nocompatible
set noswapfile
set hidden
filetype plugin indent on

" Leader
" let mapleader = " "
nnoremap <space> :


let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set number relativenumber
set showmatch
set ruler
set showcmd
set encoding=utf-8

set hlsearch ignorecase incsearch smartcase

set autoread
set backspace=indent,eol,start
set clipboard=unnamed,unnamedplus
set mouse=a
set nowrap

set showmatch
set showcmd

set cursorline
set t_Co=256
set termguicolors

syntax on
let g:onedark_termcolors=256
colorscheme onedark

" for finding files
set wildmenu
setlocal wildignore=*.pyc


