" VIMRC

set nocompatible
set noswapfile
set hidden
filetype plugin indent on

" Leader
" let mapleader = " "
nnoremap <space> :


let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set number relativenumber
set showmatch
set ruler
set showcmd
set encoding=utf-8

set hlsearch ignorecase incsearch smartcase

set autoread
set backspace=indent,eol,start
set clipboard=unnamed,unnamedplus
set mouse=a
set nowrap

set showmatch
set showcmd

set cursorline
set t_Co=256
set termguicolors

" Set cursor to line in insert mode and to block anywhere else
let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"
" Set timeout settings to 0 for smooth transition between modes
set timeoutlen=0 ttimeoutlen=0

syntax on
let g:onedark_termcolors=256
colorscheme onedark

" for finding files
set wildmenu
setlocal wildignore=*.pyc


